name: example_mobx
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1
  sqfentity: ^1.3.5+3
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  bloc_pattern: ^2.5.1
  flutter:
    sdk: flutter


dev_dependencies:
  sqfentity_gen: ^1.3.5+7
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
