// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Pessoa.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// ignore_for_file:
// BEGIN TABLES
// Pessoa TABLE
class TablePessoa extends SqfEntityTableBase {
  TablePessoa() {
    // declare properties of EntityTable
    tableName = 'Pessoa';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = true;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('idServer', DbType.integer,
          defaultValue: -1, isNotNull: false),
      SqfEntityFieldBase('sync', DbType.bool,
          defaultValue: true, isNotNull: false),
      SqfEntityFieldBase('nome', DbType.text, isNotNull: false),
      SqfEntityFieldBase('nomeFantasia', DbType.text, isNotNull: false),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TablePessoa();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class AppDatabase extends SqfEntityModelProvider {
  AppDatabase() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;
    dbVersion = myDbModel.dbVersion;
    databaseTables = [
      TablePessoa.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Pessoa
class Pessoa {
  Pessoa(
      {this.id,
      this.idServer,
      this.sync,
      this.nome,
      this.nomeFantasia,
      this.isDeleted}) {
    _setDefaultValues();
  }
  Pessoa.withFields(
      this.idServer, this.sync, this.nome, this.nomeFantasia, this.isDeleted) {
    _setDefaultValues();
  }
  Pessoa.withId(this.id, this.idServer, this.sync, this.nome, this.nomeFantasia,
      this.isDeleted) {
    _setDefaultValues();
  }
  Pessoa.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['idServer'] != null) {
      idServer = int.tryParse(o['idServer'].toString());
    }
    if (o['sync'] != null) {
      sync = o['sync'] == 1 || o['sync'] == true;
    }
    if (o['nome'] != null) {
      nome = o['nome'] as String;
    }
    if (o['nomeFantasia'] != null) {
      nomeFantasia = o['nomeFantasia'] as String;
    }
    isDeleted = o['isDeleted'] != null
        ? o['isDeleted'] == 1 || o['isDeleted'] == true
        : null;
  }
  // FIELDS (Pessoa)
  int id;
  int idServer;
  bool sync;
  String nome;
  String nomeFantasia;
  bool isDeleted;

  BoolResult saveResult;
  // end FIELDS (Pessoa)

  static const bool _softDeleteActivated = true;
  PessoaManager __mnPessoa;

  PessoaManager get _mnPessoa {
    return __mnPessoa = __mnPessoa ?? PessoaManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (idServer != null) {
      map['idServer'] = idServer;
    }

    if (sync != null) {
      map['sync'] = forQuery ? (sync ? 1 : 0) : sync;
    }

    if (nome != null) {
      map['nome'] = nome;
    }

    if (nomeFantasia != null) {
      map['nomeFantasia'] = nomeFantasia;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (idServer != null) {
      map['idServer'] = idServer;
    }

    if (sync != null) {
      map['sync'] = forQuery ? (sync ? 1 : 0) : sync;
    }

    if (nome != null) {
      map['nome'] = nome;
    }

    if (nomeFantasia != null) {
      map['nomeFantasia'] = nomeFantasia;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  /// This method returns Json String
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [idServer, sync, nome, nomeFantasia, isDeleted];
  }

  List<dynamic> toArgsWithIds() {
    return [id, idServer, sync, nome, nomeFantasia, isDeleted];
  }

  static Future<List<Pessoa>> fromWebUrl(String url) async {
    try {
      final response = await http.get(url);
      return await fromJson(response.body);
    } catch (e) {
      print('SQFENTITY ERROR Pessoa.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  static Future<List<Pessoa>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Pessoa>[];
    try {
      objList = list
          .map((pessoa) => Pessoa.fromMap(pessoa as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Pessoa.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Pessoa>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<Pessoa> objList = <Pessoa>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Pessoa.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Pessoa by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Pessoa if exist, otherwise returns null
  Future<Pessoa> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    Pessoa obj;
    final data = await _mnPessoa.getById([id]);
    if (data.length != 0) {
      obj = Pessoa.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Pessoa) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnPessoa.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnPessoa.update(this);
    }

    return id;
  }

  /// saveAs Pessoa. Returns a new Primary Key value of Pessoa

  /// <returns>Returns a new Primary Key value of Pessoa
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Pessoa> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  Future<List<dynamic>> saveAll(List<Pessoa> pessoas) async {
    // final results = _mnPessoa.saveAll('INSERT OR REPLACE INTO Pessoa (id,idServer, sync, nome, nomeFantasia,isDeleted)  VALUES (?,?,?,?,?,?)',pessoas);
    // return results; removed in sqfentity_gen 1.3.0+6
    AppDatabase().batchStart();
    for (final obj in pessoas) {
      await obj.save();
    }
    return AppDatabase().batchCommit();
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnPessoa.rawInsert(
              'INSERT OR REPLACE INTO Pessoa (id,idServer, sync, nome, nomeFantasia,isDeleted)  VALUES (?,?,?,?,?,?)',
              [id, idServer, sync, nome, nomeFantasia, isDeleted]) ==
          1) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Pessoa id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Pessoa id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Pessoa Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Pessoa>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<Pessoa> pessoas) async {
    final results = await _mnPessoa.rawInsertAll(
        'INSERT OR REPLACE INTO Pessoa (id,idServer, sync, nome, nomeFantasia,isDeleted)  VALUES (?,?,?,?,?,?)',
        pessoas);
    return results;
  }

  /// Deletes Pessoa

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Pessoa invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete || isDeleted) {
      return _mnPessoa
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnPessoa.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  /// Recover Pessoa>

  /// <returns>BoolResult res.success=Recovered, not res.success=Can not recovered
  Future<BoolResult> recover([bool recoverChilds = true]) async {
    print('SQFENTITIY: recover Pessoa invoked (id=$id)');
    {
      return _mnPessoa.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 0});
    }
  }

  PessoaFilterBuilder select(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return PessoaFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  PessoaFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return PessoaFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    idServer = idServer ?? -1;
    sync = sync ?? true;
    isDeleted = isDeleted ?? false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion pessoa

// region PessoaField
class PessoaField extends SearchCriteria {
  PessoaField(this.pessoaFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  PessoaFilterBuilder pessoaFB;

  PessoaField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  PessoaFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    pessoaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, pessoaFB.parameters, param, SqlSyntax.EQuals,
            pessoaFB._addedBlocks)
        : setCriteria(pValue, pessoaFB.parameters, param, SqlSyntax.NotEQuals,
            pessoaFB._addedBlocks);
    _waitingNot = '';
    pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
        pessoaFB._addedBlocks.retVal;
    return pessoaFB;
  }

  PessoaFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    pessoaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, pessoaFB.parameters, param,
            SqlSyntax.EQualsOrNull, pessoaFB._addedBlocks)
        : setCriteria(pValue, pessoaFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, pessoaFB._addedBlocks);
    _waitingNot = '';
    pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
        pessoaFB._addedBlocks.retVal;
    return pessoaFB;
  }

  PessoaFilterBuilder isNull() {
    pessoaFB._addedBlocks = setCriteria(
        0,
        pessoaFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        pessoaFB._addedBlocks);
    _waitingNot = '';
    pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
        pessoaFB._addedBlocks.retVal;
    return pessoaFB;
  }

  PessoaFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      pessoaFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          pessoaFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          pessoaFB._addedBlocks);
      _waitingNot = '';
      pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
          pessoaFB._addedBlocks.retVal;
    }
    return pessoaFB;
  }

  PessoaFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      pessoaFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          pessoaFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          pessoaFB._addedBlocks);
      _waitingNot = '';
      pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
          pessoaFB._addedBlocks.retVal;
      pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
          pessoaFB._addedBlocks.retVal;
    }
    return pessoaFB;
  }

  PessoaFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      pessoaFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          pessoaFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          pessoaFB._addedBlocks);
      _waitingNot = '';
      pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
          pessoaFB._addedBlocks.retVal;
    }
    return pessoaFB;
  }

  PessoaFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      pessoaFB._addedBlocks = setCriteria(
          pFirst,
          pessoaFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          pessoaFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        pessoaFB._addedBlocks = setCriteria(pFirst, pessoaFB.parameters, param,
            SqlSyntax.LessThan, pessoaFB._addedBlocks);
      } else {
        pessoaFB._addedBlocks = setCriteria(pFirst, pessoaFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, pessoaFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        pessoaFB._addedBlocks = setCriteria(pLast, pessoaFB.parameters, param,
            SqlSyntax.GreaterThan, pessoaFB._addedBlocks);
      } else {
        pessoaFB._addedBlocks = setCriteria(pLast, pessoaFB.parameters, param,
            SqlSyntax.LessThanOrEquals, pessoaFB._addedBlocks);
      }
    }
    _waitingNot = '';
    pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
        pessoaFB._addedBlocks.retVal;
    return pessoaFB;
  }

  PessoaFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    pessoaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, pessoaFB.parameters, param, SqlSyntax.GreaterThan,
            pessoaFB._addedBlocks)
        : setCriteria(pValue, pessoaFB.parameters, param,
            SqlSyntax.LessThanOrEquals, pessoaFB._addedBlocks);
    _waitingNot = '';
    pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
        pessoaFB._addedBlocks.retVal;
    return pessoaFB;
  }

  PessoaFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    pessoaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, pessoaFB.parameters, param, SqlSyntax.LessThan,
            pessoaFB._addedBlocks)
        : setCriteria(pValue, pessoaFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, pessoaFB._addedBlocks);
    _waitingNot = '';
    pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
        pessoaFB._addedBlocks.retVal;
    return pessoaFB;
  }

  PessoaFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    pessoaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, pessoaFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, pessoaFB._addedBlocks)
        : setCriteria(pValue, pessoaFB.parameters, param, SqlSyntax.LessThan,
            pessoaFB._addedBlocks);
    _waitingNot = '';
    pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
        pessoaFB._addedBlocks.retVal;
    return pessoaFB;
  }

  PessoaFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    pessoaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, pessoaFB.parameters, param,
            SqlSyntax.LessThanOrEquals, pessoaFB._addedBlocks)
        : setCriteria(pValue, pessoaFB.parameters, param, SqlSyntax.GreaterThan,
            pessoaFB._addedBlocks);
    _waitingNot = '';
    pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
        pessoaFB._addedBlocks.retVal;
    return pessoaFB;
  }

  PessoaFilterBuilder inValues(dynamic pValue) {
    pessoaFB._addedBlocks = setCriteria(
        pValue,
        pessoaFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        pessoaFB._addedBlocks);
    _waitingNot = '';
    pessoaFB._addedBlocks.needEndBlock[pessoaFB._blockIndex] =
        pessoaFB._addedBlocks.retVal;
    return pessoaFB;
  }
}
// endregion PessoaField

// region PessoaFilterBuilder
class PessoaFilterBuilder extends SearchCriteria {
  PessoaFilterBuilder(Pessoa obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Pessoa _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  PessoaFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  PessoaFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  PessoaFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  PessoaFilterBuilder where(String whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param =
          DbParameter(columnName: parameterValue == null ? null : '');
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  PessoaFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  PessoaFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  PessoaFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  PessoaFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  PessoaFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  PessoaFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  PessoaField setField(PessoaField field, String colName, DbType dbtype) {
    return PessoaField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  PessoaField _id;
  PessoaField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  PessoaField _idServer;
  PessoaField get idServer {
    return _idServer = setField(_idServer, 'idServer', DbType.integer);
  }

  PessoaField _sync;
  PessoaField get sync {
    return _sync = setField(_sync, 'sync', DbType.bool);
  }

  PessoaField _nome;
  PessoaField get nome {
    return _nome = setField(_nome, 'nome', DbType.text);
  }

  PessoaField _nomeFantasia;
  PessoaField get nomeFantasia {
    return _nomeFantasia = setField(_nomeFantasia, 'nomeFantasia', DbType.text);
  }

  PessoaField _isDeleted;
  PessoaField get isDeleted {
    return _isDeleted = setField(_isDeleted, 'isDeleted', DbType.bool);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List) {
          param.value = param.value
              .toString()
              .replaceAll('[', '')
              .replaceAll(']', '')
              .toString();
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll(
                  '?',
                  param.value is String
                      ? '\'${param.value.toString()}\''
                      : param.value.toString());
          param.value = null;
        } else {
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            whereArguments.add(param.value);
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Pessoa._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',');
  }

  /// Deletes List<Pessoa> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (Pessoa._softDeleteActivated && !hardDelete) {
      r = await _obj._mnPessoa.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnPessoa.delete(qparams);
    }
    return r;
  }

  /// Recover List<Pessoa> bulk by query
  Future<BoolResult> recover() async {
    _getIsDeleted = true;
    _buildParameters();
    print('SQFENTITIY: recover Pessoa bulk invoked');
    return _obj._mnPessoa.updateBatch(qparams, {'isDeleted': 0});
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from Pessoa ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnPessoa.updateBatch(qparams, values);
  }

  /// This method always returns Pessoa Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Pessoa>
  Future<Pessoa> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnPessoa.toList(qparams);
    final data = await objFuture;
    Pessoa obj;
    if (data.isNotEmpty) {
      obj = Pessoa.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int.
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) pessoaCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final pessoasFuture = await _obj._mnPessoa.toList(qparams);
    final int count = pessoasFuture[0]['CNT'] as int;
    if (pessoaCount != null) {
      pessoaCount(count);
    }
    return count;
  }

  /// This method returns List<Pessoa>.
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Pessoa>
  Future<List<Pessoa>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<Pessoa> pessoasData = await Pessoa.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return pessoasData;
  }

  /// This method returns Json String
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String.
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>.
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnPessoa.toList(qparams);
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnPessoa.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnPessoa.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Pessoa.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnPessoa.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion PessoaFilterBuilder

// region PessoaFields
class PessoaFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fIdServer;
  static TableField get idServer {
    return _fIdServer = _fIdServer ??
        SqlSyntax.setField(_fIdServer, 'idServer', DbType.integer);
  }

  static TableField _fSync;
  static TableField get sync {
    return _fSync = _fSync ?? SqlSyntax.setField(_fSync, 'sync', DbType.bool);
  }

  static TableField _fNome;
  static TableField get nome {
    return _fNome = _fNome ?? SqlSyntax.setField(_fNome, 'nome', DbType.text);
  }

  static TableField _fNomeFantasia;
  static TableField get nomeFantasia {
    return _fNomeFantasia = _fNomeFantasia ??
        SqlSyntax.setField(_fNomeFantasia, 'nomeFantasia', DbType.text);
  }

  static TableField _fIsDeleted;
  static TableField get isDeleted {
    return _fIsDeleted = _fIsDeleted ??
        SqlSyntax.setField(_fIsDeleted, 'isDeleted', DbType.integer);
  }
}
// endregion PessoaFields

//region PessoaManager
class PessoaManager extends SqfEntityProvider {
  PessoaManager()
      : super(AppDatabase(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'Pessoa';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion PessoaManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o) nextval]) async {
    final val = await AppDatabaseSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o) currentval]) async {
    final val = await AppDatabaseSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o) currentval]) async {
    final val = await AppDatabaseSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class AppDatabaseSequenceManager extends SqfEntityProvider {
  AppDatabaseSequenceManager() : super(AppDatabase());
}
// END OF ENTITIES
